import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { fetchEventSource } from "@microsoft/fetch-event-source";

const streamBaseURL = "http://localhost:3002";
const serverBaseURL = "http://localhost:8080";

export default function Home() {
  const [likes, setLikes] = useState(null);

  const handleLike = async() => {
    try{
      await fetch(`${serverBaseURL}/likes/update`, {method: 'POST'})
        .then((res) => res.json())
        .then((data) => {
          console.log(data);
        })
      return;
    } catch (e) {
      console.log(e);
    }
  }
  useEffect(() => {
    const fetchData = async () => {
      await fetchEventSource(`${streamBaseURL}/likes`, {
        method: "GET",
        headers: {
          Accept: "text/event-stream",
        },
        onopen(res) {
          if (res.ok && res.status === 200) {
            console.log("Connection made ", res);
          } else if (
            res.status >= 400 &&
            res.status < 500 &&
            res.status !== 429
          ) {
            console.log("Client side error ", res);
          }
        },
        onmessage(event) {
          console.log(event.data);
          const parsedData = JSON.parse(event.data);
          setLikes(parsedData.likes);
        },
        onclose() {
          console.log("Connection closed by the server");
        },
        onerror(err) {
          console.log("There was an error from server", err);
        },
      });
    };
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.likesContainer}>
          <h1>{likes}</h1>
            <button onClick={handleLike}>Like Me!!</button>
        </div>
      </main>
    </>
  )
}
